jQuery(document).ready(function(){
	var leftmenuid = $("#leftMenuID").html();
	if(leftmenuid==null||leftmenuid==""||leftmenuid=="undefined"){
		leftmenuid = "";
	}
	if(leftmenuid=="perreg"){
		$("#perregHelpMenu").removeClass("menu_check");
		$("#perfindlogpsHelpMenu").removeClass("menu_check");
		$("#pereditlogpsHelpMenu").removeClass("menu_check");
		$("#perfindpaypsHelpMenu").removeClass("menu_check");
		$("#pereditpaypsHelpMenu").removeClass("menu_check");
		$("#comregHelpMenu").removeClass("menu_check");
		$("#comfindlogpsHelpMenu").removeClass("menu_check");
		$("#comeditlogpsHelpMenu").removeClass("menu_check");
		$("#comfindpaypsHelpMenu").removeClass("menu_check");
		$("#comeditpaypsHelpMenu").removeClass("menu_check");
		$("#userenenvelopeHelpMenu").removeClass("menu_check");		
		$("#posbankflowHelpMenu").removeClass("menu_check");
		$("#posuseHelpMenu").removeClass("menu_check");
	}else if(leftmenuid=="perfindlogps"){
		$("#perregHelpMenu").removeClass("menu_check");
		$("#perfindlogpsHelpMenu").removeClass("menu_check");
		$("#pereditlogpsHelpMenu").removeClass("menu_check");
		$("#perfindpaypsHelpMenu").removeClass("menu_check");
		$("#pereditpaypsHelpMenu").removeClass("menu_check");
		$("#comregHelpMenu").removeClass("menu_check");
		$("#comfindlogpsHelpMenu").removeClass("menu_check");
		$("#comeditlogpsHelpMenu").removeClass("menu_check");
		$("#comfindpaypsHelpMenu").removeClass("menu_check");
		$("#comeditpaypsHelpMenu").removeClass("menu_check");
		$("#userenenvelopeHelpMenu").removeClass("menu_check");
		$("#posbankflowHelpMenu").removeClass("menu_check");
		$("#posuseHelpMenu").removeClass("menu_check");
	}else if(leftmenuid=="pereditlogps"){
		$("#perregHelpMenu").removeClass("menu_check");
		$("#perfindlogpsHelpMenu").removeClass("menu_check");
		$("#pereditlogpsHelpMenu").removeClass("menu_check");
		$("#perfindpaypsHelpMenu").removeClass("menu_check");
		$("#pereditpaypsHelpMenu").removeClass("menu_check");
		$("#comregHelpMenu").removeClass("menu_check");
		$("#comfindlogpsHelpMenu").removeClass("menu_check");
		$("#comeditlogpsHelpMenu").removeClass("menu_check");
		$("#comfindpaypsHelpMenu").removeClass("menu_check");
		$("#comeditpaypsHelpMenu").removeClass("menu_check");
		$("#userenenvelopeHelpMenu").removeClass("menu_check");
		$("#posbankflowHelpMenu").removeClass("menu_check");
		$("#posuseHelpMenu").removeClass("menu_check");
	}else if(leftmenuid=="perfindpayps"){
		$("#perregHelpMenu").removeClass("menu_check");
		$("#perfindlogpsHelpMenu").removeClass("menu_check");
		$("#pereditlogpsHelpMenu").removeClass("menu_check");
		$("#perfindpaypsHelpMenu").removeClass("menu_check");
		$("#pereditpaypsHelpMenu").removeClass("menu_check");
		$("#comregHelpMenu").removeClass("menu_check");
		$("#comfindlogpsHelpMenu").removeClass("menu_check");
		$("#comeditlogpsHelpMenu").removeClass("menu_check");
		$("#comfindpaypsHelpMenu").removeClass("menu_check");
		$("#comeditpaypsHelpMenu").removeClass("menu_check");
		$("#userenenvelopeHelpMenu").removeClass("menu_check");
		$("#posbankflowHelpMenu").removeClass("menu_check");
		$("#posuseHelpMenu").removeClass("menu_check");
	}else if(leftmenuid=="pereditpayps"){
		$("#perregHelpMenu").removeClass("menu_check");
		$("#perfindlogpsHelpMenu").removeClass("menu_check");
		$("#pereditlogpsHelpMenu").removeClass("menu_check");
		$("#perfindpaypsHelpMenu").removeClass("menu_check");
		$("#pereditpaypsHelpMenu").removeClass("menu_check");
		$("#comregHelpMenu").removeClass("menu_check");
		$("#comfindlogpsHelpMenu").removeClass("menu_check");
		$("#comeditlogpsHelpMenu").removeClass("menu_check");
		$("#comfindpaypsHelpMenu").removeClass("menu_check");
		$("#comeditpaypsHelpMenu").removeClass("menu_check");
		$("#userenenvelopeHelpMenu").removeClass("menu_check");
		$("#posbankflowHelpMenu").removeClass("menu_check");
		$("#posuseHelpMenu").removeClass("menu_check");
	}else if(leftmenuid=="comreg"){
		$("#perregHelpMenu").removeClass("menu_check");
		$("#perfindlogpsHelpMenu").removeClass("menu_check");
		$("#pereditlogpsHelpMenu").removeClass("menu_check");
		$("#perfindpaypsHelpMenu").removeClass("menu_check");
		$("#pereditpaypsHelpMenu").removeClass("menu_check");
		$("#comregHelpMenu").removeClass("menu_check");
		$("#comfindlogpsHelpMenu").removeClass("menu_check");
		$("#comeditlogpsHelpMenu").removeClass("menu_check");
		$("#comfindpaypsHelpMenu").removeClass("menu_check");
		$("#comeditpaypsHelpMenu").removeClass("menu_check");
		$("#userenenvelopeHelpMenu").removeClass("menu_check");
		$("#posbankflowHelpMenu").removeClass("menu_check");
		$("#posuseHelpMenu").removeClass("menu_check");
	}else if(leftmenuid=="comfindlogps"){
		$("#perregHelpMenu").removeClass("menu_check");
		$("#perfindlogpsHelpMenu").removeClass("menu_check");
		$("#pereditlogpsHelpMenu").removeClass("menu_check");
		$("#perfindpaypsHelpMenu").removeClass("menu_check");
		$("#pereditpaypsHelpMenu").removeClass("menu_check");
		$("#comregHelpMenu").removeClass("menu_check");
		$("#comfindlogpsHelpMenu").removeClass("menu_check");
		$("#comeditlogpsHelpMenu").removeClass("menu_check");
		$("#comfindpaypsHelpMenu").removeClass("menu_check");
		$("#comeditpaypsHelpMenu").removeClass("menu_check");
		$("#userenenvelopeHelpMenu").removeClass("menu_check");
		$("#posbankflowHelpMenu").removeClass("menu_check");
		$("#posuseHelpMenu").removeClass("menu_check");
	}else if(leftmenuid=="comeditlogps"){
		$("#perregHelpMenu").removeClass("menu_check");
		$("#perfindlogpsHelpMenu").removeClass("menu_check");
		$("#pereditlogpsHelpMenu").removeClass("menu_check");
		$("#perfindpaypsHelpMenu").removeClass("menu_check");
		$("#pereditpaypsHelpMenu").removeClass("menu_check");
		$("#comregHelpMenu").removeClass("menu_check");
		$("#comfindlogpsHelpMenu").removeClass("menu_check");
		$("#comeditlogpsHelpMenu").removeClass("menu_check");
		$("#comfindpaypsHelpMenu").removeClass("menu_check");
		$("#comeditpaypsHelpMenu").removeClass("menu_check");
		$("#userenenvelopeHelpMenu").removeClass("menu_check");
		$("#posbankflowHelpMenu").removeClass("menu_check");
		$("#posuseHelpMenu").removeClass("menu_check");
	}else if(leftmenuid=="comfindpayps"){
		$("#perregHelpMenu").removeClass("menu_check");
		$("#perfindlogpsHelpMenu").removeClass("menu_check");
		$("#pereditlogpsHelpMenu").removeClass("menu_check");
		$("#perfindpaypsHelpMenu").removeClass("menu_check");
		$("#pereditpaypsHelpMenu").removeClass("menu_check");
		$("#comregHelpMenu").removeClass("menu_check");
		$("#comfindlogpsHelpMenu").removeClass("menu_check");
		$("#comeditlogpsHelpMenu").removeClass("menu_check");
		$("#comfindpaypsHelpMenu").removeClass("menu_check");
		$("#comeditpaypsHelpMenu").removeClass("menu_check");
		$("#userenenvelopeHelpMenu").removeClass("menu_check");
		$("#posbankflowHelpMenu").removeClass("menu_check");
		$("#posuseHelpMenu").removeClass("menu_check");
	}else if(leftmenuid=="comeditpayps"){
		$("#perregHelpMenu").removeClass("menu_check");
		$("#perfindlogpsHelpMenu").removeClass("menu_check");
		$("#pereditlogpsHelpMenu").removeClass("menu_check");
		$("#perfindpaypsHelpMenu").removeClass("menu_check");
		$("#pereditpaypsHelpMenu").removeClass("menu_check");
		$("#comregHelpMenu").removeClass("menu_check");
		$("#comfindlogpsHelpMenu").removeClass("menu_check");
		$("#comeditlogpsHelpMenu").removeClass("menu_check");
		$("#comfindpaypsHelpMenu").removeClass("menu_check");
		$("#comeditpaypsHelpMenu").removeClass("menu_check");
		$("#userenenvelopeHelpMenu").removeClass("menu_check");
		$("#posbankflowHelpMenu").removeClass("menu_check");
		$("#posuseHelpMenu").removeClass("menu_check");
	}else if(leftmenuid=="userenenvelope"){
		$("#perregHelpMenu").removeClass("menu_check");
		$("#perfindlogpsHelpMenu").removeClass("menu_check");
		$("#pereditlogpsHelpMenu").removeClass("menu_check");
		$("#perfindpaypsHelpMenu").removeClass("menu_check");
		$("#pereditpaypsHelpMenu").removeClass("menu_check");
		$("#comregHelpMenu").removeClass("menu_check");
		$("#comfindlogpsHelpMenu").removeClass("menu_check");
		$("#comeditlogpsHelpMenu").removeClass("menu_check");
		$("#comfindpaypsHelpMenu").removeClass("menu_check");
		$("#comeditpaypsHelpMenu").removeClass("menu_check");
		$("#userenenvelopeHelpMenu").removeClass("menu_check");
		$("#posbankflowHelpMenu").removeClass("menu_check");
		$("#posuseHelpMenu").removeClass("menu_check");
	}else if(leftmenuid=="posbankflow"){
		$("#perregHelpMenu").removeClass("menu_check");
		$("#perfindlogpsHelpMenu").removeClass("menu_check");
		$("#pereditlogpsHelpMenu").removeClass("menu_check");
		$("#perfindpaypsHelpMenu").removeClass("menu_check");
		$("#pereditpaypsHelpMenu").removeClass("menu_check");
		$("#comregHelpMenu").removeClass("menu_check");
		$("#comfindlogpsHelpMenu").removeClass("menu_check");
		$("#comeditlogpsHelpMenu").removeClass("menu_check");
		$("#comfindpaypsHelpMenu").removeClass("menu_check");
		$("#comeditpaypsHelpMenu").removeClass("menu_check");
		$("#userenenvelopeHelpMenu").removeClass("menu_check");
		$("#posbankflowHelpMenu").removeClass("menu_check");
		$("#posuseHelpMenu").removeClass("menu_check");
	}else if(leftmenuid=="posuse"){
		$("#perregHelpMenu").removeClass("menu_check");
		$("#perfindlogpsHelpMenu").removeClass("menu_check");
		$("#pereditlogpsHelpMenu").removeClass("menu_check");
		$("#perfindpaypsHelpMenu").removeClass("menu_check");
		$("#pereditpaypsHelpMenu").removeClass("menu_check");
		$("#comregHelpMenu").removeClass("menu_check");
		$("#comfindlogpsHelpMenu").removeClass("menu_check");
		$("#comeditlogpsHelpMenu").removeClass("menu_check");
		$("#comfindpaypsHelpMenu").removeClass("menu_check");
		$("#comeditpaypsHelpMenu").removeClass("menu_check");
		$("#userenenvelopeHelpMenu").removeClass("menu_check");
		$("#posbankflowHelpMenu").removeClass("menu_check");
		$("#posuseHelpMenu").removeClass("menu_check");
	}else{
		$("#perregHelpMenu").removeClass("menu_check");
		$("#perfindlogpsHelpMenu").removeClass("menu_check");
		$("#pereditlogpsHelpMenu").removeClass("menu_check");
		$("#perfindpaypsHelpMenu").removeClass("menu_check");
		$("#pereditpaypsHelpMenu").removeClass("menu_check");
		$("#comregHelpMenu").removeClass("menu_check");
		$("#comfindlogpsHelpMenu").removeClass("menu_check");
		$("#comeditlogpsHelpMenu").removeClass("menu_check");
		$("#comfindpaypsHelpMenu").removeClass("menu_check");
		$("#comeditpaypsHelpMenu").removeClass("menu_check");
		$("#userenenvelopeHelpMenu").removeClass("menu_check");
		$("#posbankflowHelpMenu").removeClass("menu_check");
		$("#posuseHelpMenu").removeClass("menu_check");
	}
	if(leftmenuid!=null&&leftmenuid!=""){
		$("#"+leftmenuid+"HelpMenu").addClass("menu_check");	
	}
			
});
