UPDATE `SETTLE_PARAMETER_INFO`
SET 
 `PARAMETER_VALUE` = '10011,10012,4019,10012_c,10012_m,5024'
WHERE
	(
		`PARAMETER_TYPE` = '1000000003'
		and `PARAMETER_CODE` = 'CORRECT_FUNC_CODES'
		and `PARAMETER_VALUE` = '10011,10012,4019'
);
INSERT INTO `SETTLE_PARAMETER_INFO` (`PARAMETER_TYPE`, `PRODUCT_ID`, `PARAMETER_CODE`, `PARAMETER_VALUE`, `OBLIGATE1`, `OBLIGATE2`, `OBLIGATE3`, `STATUS_ID`, `REMARK`) VALUES ('1000000014', NULL, '4014', 'PROD_00_RS_0011', NULL, NULL, NULL, '1', '代付');
INSERT INTO `SETTLE_PARAMETER_INFO` (`PARAMETER_TYPE`, `PRODUCT_ID`, `PARAMETER_CODE`, `PARAMETER_VALUE`, `OBLIGATE1`, `OBLIGATE2`, `OBLIGATE3`, `STATUS_ID`, `REMARK`) VALUES ('1000000014', NULL, '4014', 'PROD_01_RS_0017', NULL, NULL, NULL, '1', '代付-头寸-手续费');
INSERT INTO `SETTLE_PARAMETER_INFO` (`PARAMETER_TYPE`, `PRODUCT_ID`, `PARAMETER_CODE`, `PARAMETER_VALUE`, `OBLIGATE1`, `OBLIGATE2`, `OBLIGATE3`, `STATUS_ID`, `REMARK`) VALUES ('1000000014', NULL, '4016', 'PROD_00_RS_0013', NULL, NULL, NULL, '1', '提现');
INSERT INTO `SETTLE_PARAMETER_INFO` (`PARAMETER_TYPE`, `PRODUCT_ID`, `PARAMETER_CODE`, `PARAMETER_VALUE`, `OBLIGATE1`, `OBLIGATE2`, `OBLIGATE3`, `STATUS_ID`, `REMARK`) VALUES ('1000000014', NULL, '4016', 'PROD_01_RS_0010', NULL, NULL, NULL, '1', '提现-手续费');
INSERT INTO `SETTLE_PARAMETER_INFO` (`PARAMETER_TYPE`, `PRODUCT_ID`, `PARAMETER_CODE`, `PARAMETER_VALUE`, `OBLIGATE1`, `OBLIGATE2`, `OBLIGATE3`, `STATUS_ID`, `REMARK`) VALUES ('1000000014', NULL, '4016', 'PROD_01_RS_0016', NULL, NULL, NULL, '1', '提现-头寸-手续费');
INSERT INTO `SETTLE_PARAMETER_INFO` (`PARAMETER_TYPE`, `PRODUCT_ID`, `PARAMETER_CODE`, `PARAMETER_VALUE`, `OBLIGATE1`, `OBLIGATE2`, `OBLIGATE3`, `STATUS_ID`, `REMARK`) VALUES ('1000000014', NULL, '4016', 'PROD_01_RS_0023', NULL, NULL, NULL, '1', '转账-提现');
INSERT INTO `SETTLE_PARAMETER_INFO` (`PARAMETER_TYPE`, `PRODUCT_ID`, `PARAMETER_CODE`, `PARAMETER_VALUE`, `OBLIGATE1`, `OBLIGATE2`, `OBLIGATE3`, `STATUS_ID`, `REMARK`) VALUES ('1000000014', NULL, '4013', 'PROD_00_RS_0009', NULL, NULL, NULL, '1', '代收');
INSERT INTO `SETTLE_PARAMETER_INFO` (`PARAMETER_TYPE`, `PRODUCT_ID`, `PARAMETER_CODE`, `PARAMETER_VALUE`, `OBLIGATE1`, `OBLIGATE2`, `OBLIGATE3`, `STATUS_ID`, `REMARK`) VALUES ('1000000014', NULL, '4015', 'PROD_00_RS_0012', NULL, NULL, NULL, '1', '充值');
INSERT INTO `SETTLE_PARAMETER_INFO` (`PARAMETER_TYPE`, `PRODUCT_ID`, `PARAMETER_CODE`, `PARAMETER_VALUE`, `OBLIGATE1`, `OBLIGATE2`, `OBLIGATE3`, `STATUS_ID`, `REMARK`) VALUES ('1000000014', NULL, '4015', 'PROD_01_RS_0008', NULL, NULL, NULL, '1', '充值-转账');
INSERT INTO `SETTLE_PARAMETER_INFO` (`PARAMETER_TYPE`, `PRODUCT_ID`, `PARAMETER_CODE`, `PARAMETER_VALUE`, `OBLIGATE1`, `OBLIGATE2`, `OBLIGATE3`, `STATUS_ID`, `REMARK`) VALUES ('1000000014', NULL, '4015', 'PROD_01_RS_0009', NULL, NULL, NULL, '1', '充值-手续费');
INSERT INTO `SETTLE_PARAMETER_INFO` (`PARAMETER_TYPE`, `PRODUCT_ID`, `PARAMETER_CODE`, `PARAMETER_VALUE`, `OBLIGATE1`, `OBLIGATE2`, `OBLIGATE3`, `STATUS_ID`, `REMARK`) VALUES ('1000000014', NULL, '4015', 'PROD_00_RS_0060', NULL, NULL, NULL, '1', '充值-头寸');
INSERT INTO `SETTLE_PARAMETER_INFO` (`PARAMETER_TYPE`, `PRODUCT_ID`, `PARAMETER_CODE`, `PARAMETER_VALUE`, `OBLIGATE1`, `OBLIGATE2`, `OBLIGATE3`, `STATUS_ID`, `REMARK`) VALUES ('1000000014', NULL, '4017', 'PROD_00_RS_0014', NULL, NULL, NULL, '1', '冻结');
INSERT INTO `SETTLE_PARAMETER_INFO` (`PARAMETER_TYPE`, `PRODUCT_ID`, `PARAMETER_CODE`, `PARAMETER_VALUE`, `OBLIGATE1`, `OBLIGATE2`, `OBLIGATE3`, `STATUS_ID`, `REMARK`) VALUES ('1000000014', NULL, '40171', 'PROD_00_RS_0015', NULL, NULL, NULL, '1', '冻结(授权码)');
INSERT INTO `SETTLE_PARAMETER_INFO` (`PARAMETER_TYPE`, `PRODUCT_ID`, `PARAMETER_CODE`, `PARAMETER_VALUE`, `OBLIGATE1`, `OBLIGATE2`, `OBLIGATE3`, `STATUS_ID`, `REMARK`) VALUES ('1000000014', NULL, '4018', 'PROD_00_RS_0016', NULL, NULL, NULL, '1', '解冻');
INSERT INTO `SETTLE_PARAMETER_INFO` (`PARAMETER_TYPE`, `PRODUCT_ID`, `PARAMETER_CODE`, `PARAMETER_VALUE`, `OBLIGATE1`, `OBLIGATE2`, `OBLIGATE3`, `STATUS_ID`, `REMARK`) VALUES ('1000000014', NULL, '40181', 'PROD_00_RS_0017', NULL, NULL, NULL, '1', '解冻(授权码)');
INSERT INTO `SETTLE_PARAMETER_INFO` (`PARAMETER_TYPE`, `PRODUCT_ID`, `PARAMETER_CODE`, `PARAMETER_VALUE`, `OBLIGATE1`, `OBLIGATE2`, `OBLIGATE3`, `STATUS_ID`, `REMARK`) VALUES ('1000000014', NULL, '10012_c', 'PROD_00_RS_0065', NULL, NULL, NULL, '1', '冲正');
INSERT INTO `SETTLE_PARAMETER_INFO` (`PARAMETER_TYPE`, `PRODUCT_ID`, `PARAMETER_CODE`, `PARAMETER_VALUE`, `OBLIGATE1`, `OBLIGATE2`, `OBLIGATE3`, `STATUS_ID`, `REMARK`) VALUES ('1000000014', NULL, '10012_m', 'PROD_00_RS_0021', NULL, NULL, NULL, '1', '抹账');
INSERT INTO `SETTLE_PARAMETER_INFO` (`PARAMETER_TYPE`, `PRODUCT_ID`, `PARAMETER_CODE`, `PARAMETER_VALUE`, `OBLIGATE1`, `OBLIGATE2`, `OBLIGATE3`, `STATUS_ID`, `REMARK`) VALUES ('1000000014', NULL, '10014', 'PROD_00_RS_0024', NULL, NULL, NULL, '1', '订单退款');
INSERT INTO `SETTLE_PARAMETER_INFO` (`PARAMETER_TYPE`, `PRODUCT_ID`, `PARAMETER_CODE`, `PARAMETER_VALUE`, `OBLIGATE1`, `OBLIGATE2`, `OBLIGATE3`, `STATUS_ID`, `REMARK`) VALUES ('1000000014', NULL, '10014', 'PROD_00_RS_0062', NULL, NULL, NULL, '1', '订单退款(含授权码)');
INSERT INTO `SETTLE_PARAMETER_INFO` (`PARAMETER_TYPE`, `PRODUCT_ID`, `PARAMETER_CODE`, `PARAMETER_VALUE`, `OBLIGATE1`, `OBLIGATE2`, `OBLIGATE3`, `STATUS_ID`, `REMARK`) VALUES ('1000000014', NULL, '5024', 'PROD_00_RS_0020', NULL, NULL, NULL, '1', '退票');
INSERT INTO `SETTLE_PARAMETER_INFO` (`PARAMETER_TYPE`, `PRODUCT_ID`, `PARAMETER_CODE`, `PARAMETER_VALUE`, `OBLIGATE1`, `OBLIGATE2`, `OBLIGATE3`, `STATUS_ID`, `REMARK`) VALUES ('1000000014', NULL, '4014_1', 'PROD_00_RS_0028', NULL, NULL, NULL, '1', '一分钱验证');
INSERT INTO `SETTLE_PARAMETER_INFO` (`PARAMETER_TYPE`, `PRODUCT_ID`, `PARAMETER_CODE`, `PARAMETER_VALUE`, `OBLIGATE1`, `OBLIGATE2`, `OBLIGATE3`, `STATUS_ID`, `REMARK`) VALUES ('1000000014', NULL, '4020', 'PROD_00_RS_0019', NULL, NULL, NULL, '1', '消费后退款');
INSERT INTO `SETTLE_PARAMETER_INFO` (`PARAMETER_TYPE`, `PRODUCT_ID`, `PARAMETER_CODE`, `PARAMETER_VALUE`, `OBLIGATE1`, `OBLIGATE2`, `OBLIGATE3`, `STATUS_ID`, `REMARK`) VALUES ('1000000014', NULL, '4012', 'PROD_00_RS_0007', NULL, NULL, NULL, '1', '储蓄消费');
INSERT INTO `SETTLE_PARAMETER_INFO` (`PARAMETER_TYPE`, `PRODUCT_ID`, `PARAMETER_CODE`, `PARAMETER_VALUE`, `OBLIGATE1`, `OBLIGATE2`, `OBLIGATE3`, `STATUS_ID`, `REMARK`) VALUES ('1000000014', NULL, '4014_1', 'PROD_00_RS_0064', NULL, NULL, NULL, '1', '一分钱验证');