-- 读取账户一期交易匹配订单号对应关系 原orderPackageNo弃用 改为relateOrderNo
UPDATE SETTLE_PARAMETER_INFO
	SET PARAMETER_VALUE = 'relateOrderNo'
WHERE
	PARAMETER_TYPE = '1000000009'
AND PARAMETER_VALUE = 'orderPackageNo';
-- 下游对账文件 原获取ORDER_PACKAGE_NO字段 改为 获取RELATE_ORDER_NO
UPDATE SETTLE_FILE_COLUMN
	SET FILE_COLUMN_KEY_CODE = 'RELATE_ORDER_NO'
WHERE
	SETTLE_FILE_COLUMN.FILE_COLUMN_TITLE = 'F_4'
AND SETTLE_FILE_COLUMN.FILE_COLUMN_KEY_CODE = 'ORDER_PACKAGE_NO'
-- 账户FUNC_CODE和DEAL_PRODUCT_ID对应关系添加
