/*
Navicat MySQL Data Transfer

Source Server         : settle_coding
Source Server Version : 50623
Source Host           : 121.40.166.38:3316
Source Database       : settle

Target Server Type    : MYSQL
Target Server Version : 50623
File Encoding         : 65001

Date: 2016-07-26 17:33:33
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for SETTLE_KERNEL_DETAIL_RELATION
-- ----------------------------
DROP TABLE IF EXISTS `SETTLE_KERNEL_DETAIL_RELATION`;
CREATE TABLE `SETTLE_KERNEL_DETAIL_RELATION` (
  `TRANS_KERNEL_ID` bigint(20) NOT NULL COMMENT 'SETTLE_KERNEL_ENTRY的TRANS_ID',
  `TRANS_DETAIL_ID` bigint(10) NOT NULL COMMENT 'SETTLE_TRANS_DETAIL表主键',
  `COLLECT_TYPE` int(2) NOT NULL COMMENT '汇总类型',
  `ACCOUNT_DATE` datetime NOT NULL COMMENT '账期',
  `CREATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `UPDATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`TRANS_DETAIL_ID`,`COLLECT_TYPE`,`ACCOUNT_DATE`),
  KEY `IND_ACCOUNT_DATE` (`ACCOUNT_DATE`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='SETTLE_KERNEL_ENTRY 和 SETTLE_TRANS_DETAIL 关系表';
