update SETTLE_FILE t set ROP_FILE_TYPE='79' where t.FILE_ACTIVE=1 and t.ROOT_INST_CD='M000004' and t.READ_TYPE='01' and t.FILE_PREFIX='KZ_TL_CZ';
update SETTLE_FILE t set ROP_FILE_TYPE='79' where t.FILE_ACTIVE=1 and t.ROOT_INST_CD='M000004' and t.READ_TYPE='01' and t.FILE_PREFIX='KZ_TL_CZ_HEAD';
update SETTLE_FILE t set ROP_FILE_TYPE='80' where t.FILE_ACTIVE=1 and t.ROOT_INST_CD='M000004' and t.READ_TYPE='02' and t.FILE_PREFIX='KZ_TL_FCZ';
update SETTLE_FILE t set ROP_FILE_TYPE='80' where t.FILE_ACTIVE=1 and t.ROOT_INST_CD='M000004' and t.READ_TYPE='02' and t.FILE_PREFIX='KZ_TL_FCZ_HEAD';
update SETTLE_FILE t set ROP_FILE_TYPE='81' where t.FILE_ACTIVE=1 and t.ROOT_INST_CD='M000004' and t.READ_TYPE='03' and t.FILE_PREFIX='KZ_TL_DSF';
update SETTLE_FILE t set ROP_FILE_TYPE='81' where t.FILE_ACTIVE=1 and t.ROOT_INST_CD='M000004' and t.READ_TYPE='03' and t.FILE_PREFIX='KZ_TL_DSF_HEAD';
